### ISSUE TITLE
Impossible de convertir le fichier

### ISSUE THREAD

**Issue by anamau** [etalab/csvapi#101]
Impossible de convertir le fichier situé ici : undefined

Error parsing CSV: Cannot connect to host datacat.datalocale.fr:443 ssl:default [Name or service not known] 

Identifiant : 3daa9fbc6c374197aadf97fa735e07b4

**Comment by geoffreyaldebert** [comment]
L'hôte indiqué n'est pas disponible. Nous ne pouvons donc traiter cette prévisualisation.
