### ISSUE TITLE
Impossible de convertir le fichier

### ISSUE THREAD

**Issue by mathieuclem** [etalab/csvapi#103]
Impossible de convertir le fichier situé ici : undefined

Error parsing CSV: Unsupported file type text/rtf 

Identifiant : 8f910910bf3a4df8ba1906f502644498

**Comment by geoffreyaldebert** [comment]
Bonjour, nous ne traitons que les fichiers de types csv, xls ou xlsx et donc pas de fichier de type text/rtf
