### ISSUE TITLE
Prévisualisation : Impossible de convertir le fichier

### ISSUE THREAD

**Issue by VincentAntoine** [etalab/csvapi#106]
En cliquant sur le bouton "aperçu" des données depuis la page suivante : https://www.data.gouv.fr/fr/datasets/traces-geometriques-des-ports-du-systeme-ers/
J'obtiens le message d'erreur :

> 🤕 Nous n'avons pas pu convertir ce fichier
> 
> Détails de l'erreur
>     can't start new thread

**Comment by geoffreyaldebert** [comment]
Nous avons mis à jour l'applicatif. Cela semble fonctionner à nouveau pour cet url.
