### ISSUE TITLE
Impossible de convertir le fichier

### ISSUE THREAD

**Issue by hakan9719** [etalab/csvapi#113]
Impossible de convertir le fichier situé ici : undefined

Error parsing CSV: Cannot connect to host www.cgedd.developpement-durable.gouv.frimg:443 ssl:default [Name or service not known] 

Identifiant : db1b43678e5849ef84ab3e3b6e8fbf6e

**Comment by geoffreyaldebert** [comment]
Bonjour, il s'agit d'un problème de certificat du côté du site cible et nous ne pouvons donc pas traiter cet url.
