### ISSUE TITLE
Impossible de convertir le fichier

### ISSUE THREAD

**Issue by webzines** [etalab/csvapi#114]
Impossible de convertir le fichier situé ici : undefined

Error parsing CSV: 404, message='Not Found', url=URL('https://ftp.autorite-transports.fr/Registre%20gares%20routieres.xlsx') 

Identifiant : 8e0e165365b649cda42131d4ab006f53

**Comment by geoffreyaldebert** [comment]
Le lien indiqué semble fonctionner de notre côté. Pouvez-vous retester ?
