### ISSUE TITLE
Impossible de convertir le fichier

### ISSUE THREAD

**Issue by EricViala** [etalab/csvapi#115]
Impossible de convertir le fichier situé ici : undefined

Error parsing CSV: 404, message='Not Found', url=URL('https://ciqual.anses.fr/cms/sites/default/files/inline-files/Table%20Ciqual%202020_FR_2020%2007%2007.xls') 

Identifiant : f55beee290554ab7ba968fa16084718b

**Comment by geoffreyaldebert** [comment]
Le lien indiqué semble marcher de notre côté. Pouvez-vous retester ?
