### ISSUE TITLE
Impossible de convertir le fichier

### ISSUE THREAD

**Issue by jel888** [etalab/csvapi#116]
Impossible de convertir le fichier situé ici : undefined

Error parsing CSV: Row 11921 has 28 values, but Table only has 27 columns. 

Identifiant : 9548526e43a740e89be2dc8c18f3ecf8

**Comment by geoffreyaldebert** [comment]
Pas de lien indiqué, nous ne pouvons pas savoir de quel fichier vous faites mention.

**Comment by jel888** [comment]
C'est un fichier sur le site de data.gouv.fr ici : https://www.data.gouv.fr/fr/datasets/organismes-ayant-designe-un-e-delegue-e-a-la-protection-des-donnees-dpd-dpo/ (C'est la page qui m'a fait venir ici, pas moi, alors j'ai pensé un lien était crée.)

C'est quand to clique sur "oeil" que cela fournit ce message (que j'ai envoyé en premier).
