### ISSUE TITLE
Compact JSON responses

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/csvapi#43]
Responses are not compacted, leading to higher payloads over the network.

Example: https://csvapi.data.gouv.fr/api/19aa9345f127b95cbaa0e883eb64db7d?_shape=objects&_rowid=hide&_size=50&_offset=0

**Comment by abulte** [comment]
> This function’s response will be pretty printed if it was not requested with X-Requested-With: XMLHttpRequest to simplify debugging unless the JSONIFY_PRETTYPRINT_REGULAR config parameter is set to false. Compressed (not pretty) formatting currently means no indents and no spaces after separators.

**Comment by AntoineAugusti** [comment]
Interesting!

**Comment by abulte** [comment]
Fixed directly on prod, we need no code https://gitlab.incubateur.net/data.gouv.fr/infra.data.gouv.fr/merge_requests
