### ISSUE TITLE
Specific XLS file eats up all the RAM

### ISSUE THREAD

**Issue by abulte** [etalab/csvapi#64]
Calling `/apify` on this file https://ftp.autorite-transports.fr/Donnees_transport_ferroviaire_voyageurs.xlsx will trigger crazy RAM consumption in production, until oomkiller is called.

**Comment by abulte** [comment]
Dataset is here https://www.data.gouv.fr/fr/datasets/donnees-du-transport-ferroviaire-de-voyageurs/#_

We also have to check _why_ we trigger the preview on this file, it's not on our server and the size information is not filled 🤔

**Comment by abulte** [comment]
cf https://github.com/wireservice/agate-excel/issues/42

**Comment by abulte** [comment]
> We also have to check why we trigger the preview on this file, it's not on our server and the size information is not filled 🤔

size information comes from croquemort, all clear ✅

**Comment by abulte** [comment]
@quaxsze can you make a fix based on wireservice/agate-excel#42?

**Comment by quaxsze** [comment]
One way would be to determine the file's type by looking at its signature. [For instance](https://en.wikipedia.org/wiki/List_of_file_signatures). It might be a reliable way.

**Comment by abulte** [comment]
Yes 👍

This is what the `file` command uses, right? I think we already use it, but probably not precisely enough.

>

**Comment by quaxsze** [comment]
Yes I saw this just after writing the message that's why I removed it.
