### ISSUE TITLE
Deeplink not defined or interpreted properly

### ISSUE THREAD

**Issue by abulte** [etalab/csvapi#78]
Impossible de convertir le fichier situé ici : undefined

Malformed url parameter. 

Identifiant : 418f50f8a6e442c49b77fadcbb617422

Url :

https://explore.etalab.studio/?url=https://data.london.gov.uk/download/animal-rescue-incidents-attended-by-lfb/8a7d91c2-9aec-4bde-937a-3998f4717cd8/Animal%20Rescue%20incidents%20attended%20by%20LFB%20from%20Jan%202009.csv

**Comment by abulte** [comment]
@taniki

**Comment by taniki** [comment]
https://data.london.gov.uk/dataset/animal-rescue-incidents-attended-by-lfb

**Comment by abulte** [comment]
Fixed in https://github.com/etalab/csvapi-front/commit/ae10591fe6711b3d8db10dab4c65fd480323573a
