### ISSUE TITLE
Previsualisation not working for a specific xlsx

### ISSUE THREAD

**Issue by restuccia** [etalab/csvapi#80]
This xlsx file https://www.data.gouv.fr/fr/datasets/r/501b2ac4-b70f-4ef9-9a39-c30110d09527 available on data.gouv.fr https://www.data.gouv.fr/fr/datasets/entreprises-du-patrimoine-vivant/ cannot be previsualised.

The error is `Error: Error selecting data(no such table: 98ab00a6e4337df26ac43d395d7bc918)`

**Comment by abulte** [comment]
<img width="533" alt="Capture d’écran 2022-03-08 à 11 58 59" src="https://user-images.githubusercontent.com/119625/157225517-b4b1f1bf-acc0-4285-a4ed-6455e0c5e1be.png">

The file is pretty messed up, so we won't try to fix it. Still, we need to fail gracefully.
