### ISSUE TITLE
Preview does not work when the MIME type is wrong

### ISSUE THREAD

**Issue by restuccia** [etalab/csvapi#83]
Probably not a bug, but when a csv has the wrong MIME type, csvapi returns an error, e.g. `Error: Error parsing CSV: Unsupported file type application/octet-stream` when trying to open an `application/octet-stream` file.

I encountered the bug in the following dataset on data.gouv.fr https://www.data.gouv.fr/fr/datasets/liste-des-engagements-du-plan-daction-partenariat-pour-un-gouvernement-ouvert-open-government-partnership/
One of the two ressources is a correctly generated CSV file with `text/plain` MIME type, the other one is still a csv, with the `application/octet-stream` MIME (I don't know why).

Uploading the files here in case they change on data.gouv.fr
[jalons-export-20220215.csv](https://github.com/etalab/csvapi/files/8364395/jalons-export-20220215.csv)
[engagements-export-20220215.csv](https://github.com/etalab/csvapi/files/8364393/engagements-export-20220215.csv)

**Comment by geoffreyaldebert** [comment]
pas sûr que ce soit une bonne idée de commencer à traiter des fichiers avec un format autre que les formats classiques de csv (octet-stream par exemple). Je propose de fermer l'issue pour le moment. Nous verrons si dans le futur ce besoin est nécessaire.
