### ISSUE TITLE
Bench csvapi sur de multiples messages kafka

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/csvapi#87]

**Comment by sixtedemaupeou** [comment]
Reste à mettre en place les tests de charge avant de passer en done.

**Comment by sixtedemaupeou** [comment]
Inclus https://github.com/orgs/etalab/projects/6/views/33

**Comment by geoffreyaldebert** [comment]
Faire un benchmark également sur la nouvelle archi avec tests.

**Comment by geoffreyaldebert** [comment]
Kafka out pour le moment. On close.
