### ISSUE TITLE
Impossible de convertir le fichier

### ISSUE THREAD

**Issue by fredericnavarro** [etalab/csvapi#88]
Impossible de convertir le fichier situé ici : undefined

Error parsing CSV: Row 12334 has 28 values, but Table only has 27 columns. 

Identifiant : ea0d1162012d4282a07adcc7a12484d6

**Comment by abulte** [comment]
Bonjour,

Avez-vous l'URL du jeu de données concerné ?

Merci.

**Comment by fredericnavarro** [comment]
Bonsoir;

Désolé, je me souviens plus du context
