### ISSUE TITLE
Impossible de convertir le fichier

### ISSUE THREAD

**Issue by loichay** [etalab/csvapi#90]
Impossible de convertir le fichier situé ici : undefined

Error parsing CSV: File too big (max size is 104857600 bytes) 

Identifiant : ca0d309be8ea4869a8e495710da879b1

**Comment by abulte** [comment]
Le fichier est donc trop lourd :-) Pour assurer la scalabilité du service nous restreignons à 100Mo.

Voir https://github.com/etalab/csvapi/issues/95 pour une possible augmentation de la taille.

Aussi nous ne proposerons bientôt plus le bouton "prévisualiser" si le fichier est effectivement trop lourd (aujourd'hui c'est seulement le cas si la taille est renseignée dans les métadonnées).
