### ISSUE TITLE
Impossible de convertir le fichier

### ISSUE THREAD

**Issue by gmat** [etalab/csvapi#91]
Impossible de convertir le fichier situé ici : https://www.data.gouv.fr/fr/datasets/r/f0b85156-91c2-4c8a-9b3f-beda48d15ecd

resultats-definitifs-par-bureau-de-vote.xlsx 
pour Résultats des élections européennes 2019

**Comment by abulte** [comment]
Le fichier est trop lourd (presque 100Mo) pour être converti correctement. Cf https://github.com/etalab/csvapi/issues/94 pour une solution possible.
